language: julia
sudo: required
dist: trusty

os:
    - linux

arch:
    - amd64

services:
    - neo4j

julia:
    - 1.2
    - 1.4
    - nightly

env:
    - IIF_TEST=false

jobs:
  include:
    - julia: 1.3
      env: IIF_TEST=true
      if: NOT branch =~ ^release.*$
    - arch: arm64
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
  fast_finish: true

notifications:
    email: false

matrix:
  allow_failures:
  - julia: nightly
  - arch: arm64
  - env: IIF_TEST=true

# Set the password for Neo4j to neo4j:test
before_script:
    - sleep 10
    - curl -v POST http://neo4j:neo4j@localhost:7474/user/neo4j/password -d"password=test"

after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("DistributedFactorGraphs")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
